### ISSUE TITLE
Build/compilation troubles

### ISSUE THREAD

**Issue by chessturo** [FriedrichFroebel/python-djvulibre#20]
Hey!

Not a python dev, so there's a decent possibility my deps are just messed up, so please bear with me. It appears cython is having issues with one of the source files
```
      generating build/temp.linux-x86_64-3.10/src/sexpr.c from djvu/sexpr.pyx, build/temp.linux-x86_64-3.10/src/config.pxi, djvu/common.pxi, djvu/sexpr.pxd, djvu/decode.pxd

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          @cython.final
          cdef cexpr_t printw(self, cexpr_t cexpr, int width):
              return cexpr_printw(&self.cio, cexpr, width)

      cdef int _myio_puts(cexpr_io_t* cio, const char *s) noexcept:
                                                         ^
      ------------------------------------------------------------

      djvu/sexpr.pyx:150:52: Syntax error in C variable declaration
```

Output of `cython --version` is `Cython version 0.29.14`; please let me know if you have any thoughts/ideas. Thanks!

EDIT: Also tried with `cython --version` of `Cython version 3.0.11`. Still no dice, unfortunately.

**Comment by FriedrichFroebel** [comment]
The error looks like some Cython version issue in your build.

Could you please elaborate how you are installing the package? `pip install --no-cache djvulibre-python` works for me on Python 3.12. In theory, there should be no need to install Cython manually, as the build fetches it automatically (Cython 3.0.11 in my case).

**Comment by chessturo** [comment]
Ah, I eventually found the underlying issue. I had a (very) old version of cython installed via `apt` that satisfied the version requirement that pip was seeing (I had `Cython 0.29.28`, `pyproject.toml` has the requirement `>=0.28`). I guess that even when I installed the newer version of cython manually via pip, it still wanted to use the `apt`-installed version.

Thank you for your help!
